# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d00e51466b588ecc27f0806b1a51c8bafc58a2ede3199f6b6d3db58f2a6d3dd44e763a99a89b78b2621fc4c61211f615a1481573fa99587127bde7d2140d6a0

test:
  secret_key_base: 9b2383c575234d62b52bcd7c9a6e5b415a8adaf8686566be0080c53ff630192fda3ae894830bb1181560257bb81de29c177d81e6be3d9ce18c57a7c258f2e8ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
